# Generated by Django 5.0.2 on 2024-02-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='msg',
        ),
        migrations.AddField(
            model_name='travel',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='code',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='phoneno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='pincode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='rights',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='travel',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
