# Generated by Django 5.0.2 on 2024-04-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_travel_msg_travel_address_travel_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='code',
        ),
    ]
