# Generated by Django 5.0.2 on 2024-04-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
