# Generated by Django 5.0.2 on 2024-04-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_packages_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('fullname', models.CharField(max_length=50)),
                ('checkin', models.DateField()),
                ('cno', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('exp', models.DateField()),
            ],
        ),
    ]
