# Generated by Django 5.0.2 on 2024-04-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
