# Generated by Django 5.0.2 on 2024-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_bookings_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='bdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
